spring:
  application:
    name: applink-api

  web:
    cors:
      allowed-origin-patterns: "*"
      allowed-headers: "*"
      allowed-methods: "*"
      allow-credentials: true

  datasource:
    url: jdbc:postgresql://localhost:5432/applink
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000