spring:
  application:
    name: applink-api

  datasource:
    url: jdbc:postgresql://localhost:5432/applink
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration